// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/AkankshaNichrelay/TableFinder/internal/cache"
	"github.com/AkankshaNichrelay/TableFinder/internal/config"
	"github.com/AkankshaNichrelay/TableFinder/internal/database"
	"github.com/AkankshaNichrelay/TableFinder/internal/handler"
	"github.com/AkankshaNichrelay/TableFinder/internal/redis"
	"github.com/AkankshaNichrelay/TableFinder/internal/restaurant"
	"github.com/google/wire"
	"log"
)

// Injectors from wire.go:

func InitializeAndRun(ctx context.Context, logger *log.Logger, configFile string) (*handler.Handler, error) {
	configConfig, err := config.New(configFile)
	if err != nil {
		return nil, err
	}
	redisConfig := config.NewRedisConfig(configConfig)
	client := redis.New(logger, redisConfig)
	cacheClient := cache.New(client)
	databaseConfig := config.NewDBConfig(configConfig)
	mySQL, err := database.New(logger, databaseConfig)
	if err != nil {
		return nil, err
	}
	restaurants := restaurant.New(cacheClient, mySQL)
	handlerHandler := handler.New(logger, restaurants)
	return handlerHandler, nil
}

// wire.go:

// cacheSet associates redis client struct with cacheAccessor interface
var cacheSet = wire.NewSet(redis.New, wire.Bind(new(cache.Accessor), new(*redis.Client)))

var dbSet = wire.NewSet(database.New, wire.Bind(new(database.DBAccessor), new(*database.MySQL)))
